#!/bin/bash -l

#SBATCH -t 02:30:00
#SBATCH -N 15
#SBATCH -A m558_g
#SBATCH -q regular
#SBATCH -C gpu
#SBATCH --exclusive
#SBATCH --gpu-bind=none
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node=4

# Treat unset variables as an error when performing parameter expansion and
# exit immediately if a command exits with a non-zero status or if a pipeline fails
set -o nounset errexit pipefail

# Source environment
source $HOME/db.profile
source $HOME/perlmutter_gpu_warpx.profile

# Run optimas scan
python templates/run_grid_scan.py
