#!/bin/bash -l

#SBATCH -t 04:00:00
#SBATCH -N 60
#SBATCH -A m558_g
#SBATCH -q regular
#SBATCH -C gpu
#SBATCH --exclusive
#SBATCH --gpu-bind=none
#SBATCH --ntasks-per-node=4

# Source environment
source $HOME/db.profile
source $HOME/perlmutter_gpu_warpx.profile

# Run optimas scan
python templates/run_grid_scan.py
