#!/bin/bash -l

#SBATCH -t 00:15:00
#SBATCH -N 1
#SBATCH -A m558_g
#SBATCH -q debug
#SBATCH -C gpu
#SBATCH --exclusive
#SBATCH --gpu-bind=none
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node=4
#SBATCH -o /global/cfs/cdirs/m558/superfacility/simulation_running/staging_injector/logs/run.o%j
#SBATCH -e /global/cfs/cdirs/m558/superfacility/simulation_running/staging_injector/logs/run.e%j

# Source environment
source $HOME/db.profile
source $HOME/perlmutter_gpu_warpx.profile

# Run single simulation
cd /global/cfs/cdirs/m558/superfacility/simulation_running/staging_injector
srun python templates/run_grid_scan.py --single-simulation-parameters templates/single_simulation_parameters.yaml