#!/bin/bash -l

#SBATCH -t 00:15:00
#SBATCH -N 3
#SBATCH -A m558_g
#SBATCH -q debug
#SBATCH -C gpu
#SBATCH --exclusive
#SBATCH --gpu-bind=none
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-node=4

# Source environment
source $HOME/db.profile
source $HOME/perlmutter_gpu_warpx.profile

#Go to cfs superfacility
cd /global/cfs/cdirs/m558/superfacility/simulation_data/acave

# Create new directory
mkdir single_$SLURM_JOB_ID
cd single_$SLURM_JOB_ID

# Run optimas scan
python ../templates/run_grid_scan.py --single-simulation-parameters ../single_sim_vals.csv
